apiVersion: v1
kind: Service
metadata:
  name: prestashop-site-id
  labels:
    app.kubernetes.io/app: prestashop-site-id
    app.kubernetes.io/instance: prestashop-site-id
    app.kubernetes.io/component: website
    app.kubernetes.io/part-of: prestashop
    app.kubernetes.io/managed-by: prestashop-operator
spec:
  ports:
    - port: 80
      name: http
  clusterIP: None
  selector:
    app: prestashop